spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/jwt_security
        driver-class-name: org.postgresql.Driver
        username: postgres
        password:
    jpa:
        hibernate:
            ddl-auto: create-drop #this is on startup
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect


application:
    security:
        jwt:
            secret-key: UVBVaHZ1RHlyelNaRWdWdnpXVFVEckloWmI0OXhJWXRDdTcraXM0aEVRVT0
            expiration: 86400000 # a day
            